### PR TITLE
add quick way to use own app

### LINKED ISSUE #37: Google denies access (current GitHub version)
I tried the CRAN version and everything works as expected. (Its a wonderful package sofar, thanks!!!)
But when I upgrade to your current master version on GitHub, using:

`remotes::install_github("claudiozandonella/trackdown", build_vignettes = TRUE)`

I cannot use trackdown functions anymore like:
```
 path <- "1_paper/1_paper.Rmd"
upload_file(file = path, hide_code = TRUE)
update_file(file = path, hide_code = TRUE)
download_file(file = path)
```
I get in R the following error: 

> Error in curl::curl_fetch_memory(url, handle = handle) : 
> Could not resolve host: metadata.google.internal

and from Goofle I get this message: 

> This app is blocked
> This app has attempted to access sensitive data in your Google Account. To protect your account, we have blocked access.

grafik

Could you give more details how to solve this problem (maybe even add it to the vignette)? Because the changes on the master branch are really great and I would love to use them!!! ♥

### PR DESCRIPTION
**Pull request by maelle**
Fix #37 

As far as I understand, currently trackdown uses credentials that are saved in sysdata.rda.

Still WIP, untested beyond checking what `active_trackdown_app()` returns, as I haven't created an app in Google Cloud dashboard yet. It's also not necessarily the best way to use one's own app: it'd be nice to have a function as in gmailr https://gmailr.r-lib.org/articles/gmailr.html#external-setup `gmailr::gm_auth_configure()`.

With this fork one would run

```r
my_app_name <- "trackdown-rpackage-fork"
my_app_secret <- "GOCSblablabla"
my_app_key <- "blablablabla.apps.googleusercontent.com"

my_app <- httr::oauth_app(
  appname = my_app_name,
  secret = my_app_secret,
  key = my_app_key
)

options("trackdown-app" = my_app)
```

Cc @krlmlr

### CODE REVIEW

**Comment by maelle** [comment]
better way = https://gargle.r-lib.org/articles/gargle-auth-in-client-package.html

**Comment by ClaudioZandonella** [comment]
Hi @maelle 

Thank you very much for this PR, it is exactly what we need!❤️ 

I am reviewing right now all the possibilities to allow access with the user's own credentials. 
I will merge your pull request after adding the required documentation. 

Thank you again for your help

**Comment by maelle** [comment]
I think my PR is a bit of a hack though, it'd be better not to merge it and to follow the step in https://gargle.r-lib.org/articles/gargle-auth-in-client-package.html#overview-of-mechanics :innocent:

**Comment by ClaudioZandonella** [comment]
Hi @maelle,

After reviewing the documentation of gargle, gmailr, and googledrive, I think a mix of your approach and the one described in the documentation is the best solution. According to my understanding, here few points to consider [these are actually notes for myself to summarize the problem and avoid forgetting😅]:

- It is not possible to use API key credentials. Trackdown requires OAuth2 token credentials to access and modify users' files in Google Drive. 
- To obtain OAuth2 token credentials for Google APIs it is necessary to create a Google Cloud Platform (GCP) project and create an OAuth client ID. 
- We created a GCP project for trackdown and obtained the OAuth client ID for using the Google APIs, however, Google allows only a limited number of users for each project (up to 100). After that, a verification from Google is required. Unfortunately, we failed to obtain Google verification of our app (they require a GUI with logos etc. and it is not possible to do that in the R command line). Now we reached the max number of users, so new users can not utilize trackdown.
- The solution is to allow users to utilize their own app credentials as you proposed.
- I will change a little bit your code to follow the steps described in gargle documentation and create a similar approach as the one used by gmailr. 
- I will also add a step-by-step guide that users can follow to create the Google Cloud Platform (GCP) project and OAuth client ID with the required scopes.

I hope the final procedure will not be too complicated for the users and hopefully, in the future, we will succeed in the google verification.

I will update  when all changes are ready. 
Thanks again for your help❤️

**Comment by ClaudioZandonella** [comment]
hi @maelle 

I just released a new version of trakdown that allow using custom app credentials. Unfortunately, it is necessary that users create their own app. I added a detailed guide here https://claudiozandonella.github.io/trackdown/articles/oauth-app-configuration.html

Let me know if it is now usable or if more details are needed (there is no such a thing as too much documentation 😅)

Hopefully, in the future, we will be able to pass google authentication process

I do not why you do not appear as a contributor as well. I changed dramatically the code, but there is still your commit. I will fix it tomorrow.

Thanks again for your suggestions❤️

**Comment by maelle** [comment]
wow I see you made a ton of progress on this, awesome to see! Thank _you_!!

**Pull request merged**
